# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-02 02:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0008_album_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='category',
            field=models.IntegerField(blank=True, default=4, null=True),
        ),
        migrations.AlterField(
            model_name='album',
            name='description',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='One Line Description'),
        ),
        migrations.AlterField(
            model_name='album',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
